server:
  port: 8080
  servlet:
    context-path: /api


spring:
  datasource:
    url: jdbc:h2:mem:bookdb
    driver-class-name: org.h2.Driver
    username: admin
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console


logging:
  level:
    com.BookApi.exception: WARN
    org.springframework.web: DEBUG
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql: trace
